"""add_registries_and_expand_metric

Revision ID: 45460b743918
Revises: 58e138959809
Create Date: 2026-06-10 16:45:39.016592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45460b743918'
down_revision: Union[str, Sequence[str], None] = '58e138959809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('specifications', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('lifecycle_stage_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantity_kinds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('qudt_uri', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=64), nullable=True),
    sa.Column('capabilities', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('auth_method', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('metadata_info', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('quantity_kind_id', sa.Integer(), nullable=False),
    sa.Column('si_base', sa.Boolean(), nullable=False),
    sa.Column('canonical_unit_id', sa.Integer(), nullable=True),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('conversion_offset', sa.Float(), nullable=False),
    sa.Column('qudt_uri', sa.String(length=256), nullable=True),
    sa.Column('saref_uri', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['canonical_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['quantity_kind_id'], ['quantity_kinds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('cim_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('cim_metric_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=True),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cim_metric_id'], ['metric_definitions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cim_mappings_cim_metric_id'), 'cim_mappings', ['cim_metric_id'], unique=False)
    op.create_index(op.f('ix_cim_mappings_source_id'), 'cim_mappings', ['source_id'], unique=False)
    op.create_index(op.f('ix_cim_mappings_source_key'), 'cim_mappings', ['source_key'], unique=False)
    op.create_index(op.f('ix_cim_mappings_standard_id'), 'cim_mappings', ['standard_id'], unique=False)
    op.alter_column('categories', 'standard_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.create_foreign_key('categories_standard_id_fkey', 'categories', 'standards', ['standard_id'], ['id'], ondelete='SET NULL')
    op.drop_column('categories', 'auto_created')
    op.drop_constraint(op.f('file_upload_logs_datacenter_id_fkey'), 'file_upload_logs', type_='foreignkey')
    op.create_foreign_key('file_upload_logs_datacenter_id_fkey', 'file_upload_logs', 'datacenters', ['datacenter_id'], ['id'], ondelete='CASCADE')
    op.add_column('metric_definitions', sa.Column('label', sa.String(length=255), nullable=True))
    op.add_column('metric_definitions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('metric_definitions', sa.Column('domain', sa.String(length=64), nullable=True))
    op.add_column('metric_definitions', sa.Column('quantity_kind_id', sa.Integer(), nullable=True))
    op.add_column('metric_definitions', sa.Column('canonical_unit_id', sa.Integer(), nullable=True))
    op.add_column('metric_definitions', sa.Column('metric_type', sa.String(length=64), nullable=True))
    op.add_column('metric_definitions', sa.Column('status', sa.String(length=64), server_default='draft', nullable=False))
    op.add_column('metric_definitions', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('metric_definitions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('metric_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('metric_definitions_canonical_unit_id_fkey', 'metric_definitions', 'units', ['canonical_unit_id'], ['id'])
    op.create_foreign_key('metric_definitions_quantity_kind_id_fkey', 'metric_definitions', 'quantity_kinds', ['quantity_kind_id'], ['id'])
    op.drop_index(op.f('ix_metric_keywords_source_key_lower'), table_name='metric_keywords')
    op.drop_index(op.f('uq_metric_keywords_keyword_lower'), table_name='metric_keywords')
    
    # Clean up NULL values before altering columns to NOT NULL
    op.execute("UPDATE metric_samples SET tags = '{}' WHERE tags IS NULL")
    op.execute("UPDATE metric_samples SET extra_meta = '{}' WHERE extra_meta IS NULL")
    
    op.alter_column('metric_samples', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('metric_samples', 'ri_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('metric_samples', 'node_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('metric_samples', 'vm_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('metric_samples', 'host',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('metric_samples', 'site_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('metric_samples', 'clf_confidence',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'extra_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.drop_index(op.f('ix_metric_samples_domain'), table_name='metric_samples')
    op.drop_constraint(op.f('standards_name_key'), 'standards', type_='unique')
    op.drop_index(op.f('uq_subcategories_catid_name_lower'), table_name='subcategories')
    op.drop_column('subcategories', 'auto_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('auto_created', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_index(op.f('uq_subcategories_catid_name_lower'), 'subcategories', ['category_id', sa.literal_column('lower(name::text)')], unique=True)
    op.create_unique_constraint(op.f('standards_name_key'), 'standards', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_metric_samples_domain'), 'metric_samples', ['domain'], unique=False)
    op.alter_column('metric_samples', 'extra_meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('metric_samples', 'clf_confidence',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'site_id',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'host',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'vm_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'node_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'ri_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('uq_metric_keywords_keyword_lower'), 'metric_keywords', ['keyword'], unique=True)
    op.create_index(op.f('ix_metric_keywords_source_key_lower'), 'metric_keywords', ['source_key'], unique=False)
    op.drop_constraint('metric_definitions_canonical_unit_id_fkey', 'metric_definitions', type_='foreignkey')
    op.drop_constraint('metric_definitions_quantity_kind_id_fkey', 'metric_definitions', type_='foreignkey')
    op.alter_column('metric_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('metric_definitions', 'updated_at')
    op.drop_column('metric_definitions', 'version')
    op.drop_column('metric_definitions', 'status')
    op.drop_column('metric_definitions', 'metric_type')
    op.drop_column('metric_definitions', 'canonical_unit_id')
    op.drop_column('metric_definitions', 'quantity_kind_id')
    op.drop_column('metric_definitions', 'domain')
    op.drop_column('metric_definitions', 'description')
    op.drop_column('metric_definitions', 'label')
    op.drop_constraint('file_upload_logs_datacenter_id_fkey', 'file_upload_logs', type_='foreignkey')
    op.create_foreign_key(op.f('file_upload_logs_datacenter_id_fkey'), 'file_upload_logs', 'datacenters', ['datacenter_id'], ['id'])
    op.add_column('categories', sa.Column('auto_created', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint('categories_standard_id_fkey', 'categories', type_='foreignkey')
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.alter_column('categories', 'standard_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_cim_mappings_standard_id'), table_name='cim_mappings')
    op.drop_index(op.f('ix_cim_mappings_source_key'), table_name='cim_mappings')
    op.drop_index(op.f('ix_cim_mappings_source_id'), table_name='cim_mappings')
    op.drop_index(op.f('ix_cim_mappings_cim_metric_id'), table_name='cim_mappings')
    op.drop_table('cim_mappings')
    op.drop_table('units')
    op.drop_table('sources')
    op.drop_table('quantity_kinds')
    op.drop_table('assets')
    # ### end Alembic commands ###
