"""initial_schema

Revision ID: 58e138959809
Revises: 
Create Date: 2026-06-10 16:42:36.036032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58e138959809'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'standard_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_foreign_key(None, 'categories', 'standards', ['standard_id'], ['id'], ondelete='SET NULL')
    op.drop_column('categories', 'auto_created')
    op.drop_constraint(op.f('file_upload_logs_datacenter_id_fkey'), 'file_upload_logs', type_='foreignkey')
    op.create_foreign_key(None, 'file_upload_logs', 'datacenters', ['datacenter_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_metric_keywords_source_key_lower'), table_name='metric_keywords')
    op.drop_index(op.f('uq_metric_keywords_keyword_lower'), table_name='metric_keywords')
    op.alter_column('metric_samples', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('metric_samples', 'ri_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('metric_samples', 'node_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('metric_samples', 'vm_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('metric_samples', 'host',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('metric_samples', 'site_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('metric_samples', 'clf_confidence',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'extra_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.drop_index(op.f('ix_metric_samples_domain'), table_name='metric_samples')
    op.drop_constraint(op.f('standards_name_key'), 'standards', type_='unique')
    op.drop_index(op.f('uq_subcategories_catid_name_lower'), table_name='subcategories')
    op.drop_column('subcategories', 'auto_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('auto_created', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_index(op.f('uq_subcategories_catid_name_lower'), 'subcategories', ['category_id', sa.literal_column('lower(name::text)')], unique=True)
    op.create_unique_constraint(op.f('standards_name_key'), 'standards', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_metric_samples_domain'), 'metric_samples', ['domain'], unique=False)
    op.alter_column('metric_samples', 'extra_meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('metric_samples', 'clf_confidence',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'site_id',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'host',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'vm_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'node_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'ri_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metric_samples', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('uq_metric_keywords_keyword_lower'), 'metric_keywords', ['keyword'], unique=True)
    op.create_index(op.f('ix_metric_keywords_source_key_lower'), 'metric_keywords', ['source_key'], unique=False)
    op.drop_constraint(None, 'file_upload_logs', type_='foreignkey')
    op.create_foreign_key(op.f('file_upload_logs_datacenter_id_fkey'), 'file_upload_logs', 'datacenters', ['datacenter_id'], ['id'])
    op.add_column('categories', sa.Column('auto_created', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='unique')
    op.alter_column('categories', 'standard_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
