"""drop_legacy_tables

Revision ID: a7708d6bee50
Revises: 270d7d8ed609
Create Date: 2026-06-10 16:59:41.856153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7708d6bee50'
down_revision: Union[str, Sequence[str], None] = '270d7d8ed609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_source_map')
    op.drop_table('metric_keywords')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subcategory', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('short_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('metric_keywords_pkey')),
    sa.UniqueConstraint('keyword', name=op.f('metric_keywords_keyword_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('metric_source_map',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('datacenter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raw_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unified_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['datacenter_id'], ['datacenters.id'], name=op.f('metric_source_map_datacenter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('metric_source_map_pkey')),
    sa.UniqueConstraint('datacenter_id', 'raw_key', name=op.f('uq_dc_rawkey'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
